// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrWFan2eYOa0huWs1gixDLmF1zuUJako',
    appId: '1:504738132804:web:2a64d57a551a9f086b9d11',
    messagingSenderId: '504738132804',
    projectId: 'chat-app-6d609',
    authDomain: 'chat-app-6d609.firebaseapp.com',
    storageBucket: 'chat-app-6d609.appspot.com',
    measurementId: 'G-N9GCPD0MRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2OTvRci-oMLuHOorOroZ8XVqB1PesY-g',
    appId: '1:504738132804:android:97fb6b4ac0f668926b9d11',
    messagingSenderId: '504738132804',
    projectId: 'chat-app-6d609',
    storageBucket: 'chat-app-6d609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVMczzJF-AKNj4Rd9yn5HCyxmdvsSGPx0',
    appId: '1:504738132804:ios:cd870aad6a1b39b76b9d11',
    messagingSenderId: '504738132804',
    projectId: 'chat-app-6d609',
    storageBucket: 'chat-app-6d609.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVMczzJF-AKNj4Rd9yn5HCyxmdvsSGPx0',
    appId: '1:504738132804:ios:cd870aad6a1b39b76b9d11',
    messagingSenderId: '504738132804',
    projectId: 'chat-app-6d609',
    storageBucket: 'chat-app-6d609.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvrWFan2eYOa0huWs1gixDLmF1zuUJako',
    appId: '1:504738132804:web:a48b74f89b135f7e6b9d11',
    messagingSenderId: '504738132804',
    projectId: 'chat-app-6d609',
    authDomain: 'chat-app-6d609.firebaseapp.com',
    storageBucket: 'chat-app-6d609.appspot.com',
    measurementId: 'G-TEMDC2LVRQ',
  );
}
